name: panda-express-dashboard
region: fra

# Backend Web Service
services:
  - name: backend
    source_dir: backend
    github:
      repo: olegkuftyrev/1020
      branch: main
      deploy_on_push: true
    
    build_command: npm ci && npx prisma migrate deploy && npm run build
    run_command: npm start
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 3333
    
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3333"
      - key: HOST
        value: "0.0.0.0"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_TIME
        type: SECRET
      - key: AUTH_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: APP_KEY
        scope: RUN_TIME
        type: SECRET
      - key: WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: LOG_LEVEL
        value: info
    
    health_check:
      http_path: /api/auth/verify
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

# Frontend Static Site
static_sites:
  - name: frontend
    source_dir: frontend
    github:
      repo: olegkuftyrev/1020
      branch: main
      deploy_on_push: true
    
    build_command: npm ci && npm run build
    output_dir: dist
    
    envs:
      - key: VITE_API_URL
        value: ${backend.PUBLIC_URL}/api
        scope: BUILD_TIME

# Database (PostgreSQL)
databases:
  - name: db
    engine: PG
    production: true
    version: "15"

